// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeBytes, SchemaType: map[string]string{"mysql": "json", "postgres": "jsonb", "sqlite3": "json"}},
		{Name: "tags", Type: field.TypeBytes, SchemaType: map[string]string{"mysql": "json", "postgres": "jsonb", "sqlite3": "json"}},
		{Name: "profile", Type: field.TypeJSON},
		{Name: "password", Type: field.TypeString},
		{Name: "api_secret", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
