// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ubgo/entkit/encryptedtype"
	"github.com/ubgo/entkit/examples/ent/user"
	"github.com/ubgo/entkit/jsonmap"
	"github.com/ubgo/entkit/passwordtype"
	"github.com/ubgo/jsonslice"
	"github.com/ubgo/jsontype"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata jsonmap.JsonMap `json:"metadata,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags jsonslice.JsonSlice `json:"tags,omitempty"`
	// Profile holds the value of the "profile" field.
	Profile jsontype.JSON `json:"profile,omitempty"`
	// Password holds the value of the "password" field.
	Password passwordtype.HashedPassword `json:"-"`
	// APISecret holds the value of the "api_secret" field.
	APISecret    encryptedtype.EncryptedString `json:"-"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldAPISecret:
			values[i] = new(encryptedtype.EncryptedString)
		case user.FieldMetadata:
			values[i] = new(jsonmap.JsonMap)
		case user.FieldTags:
			values[i] = new(jsonslice.JsonSlice)
		case user.FieldProfile:
			values[i] = new(jsontype.JSON)
		case user.FieldPassword:
			values[i] = new(passwordtype.HashedPassword)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldMetadata:
			if value, ok := values[i].(*jsonmap.JsonMap); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil {
				_m.Metadata = *value
			}
		case user.FieldTags:
			if value, ok := values[i].(*jsonslice.JsonSlice); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil {
				_m.Tags = *value
			}
		case user.FieldProfile:
			if value, ok := values[i].(*jsontype.JSON); !ok {
				return fmt.Errorf("unexpected type %T for field profile", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Profile); err != nil {
					return fmt.Errorf("unmarshal field profile: %w", err)
				}
			}
		case user.FieldPassword:
			if value, ok := values[i].(*passwordtype.HashedPassword); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value != nil {
				_m.Password = *value
			}
		case user.FieldAPISecret:
			if value, ok := values[i].(*encryptedtype.EncryptedString); !ok {
				return fmt.Errorf("unexpected type %T for field api_secret", values[i])
			} else if value != nil {
				_m.APISecret = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("profile=")
	builder.WriteString(fmt.Sprintf("%v", _m.Profile))
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("api_secret=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
