// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldProfile holds the string denoting the profile field in the database.
	FieldProfile = "profile"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldAPISecret holds the string denoting the api_secret field in the database.
	FieldAPISecret = "api_secret"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldMetadata,
	FieldTags,
	FieldProfile,
	FieldPassword,
	FieldAPISecret,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByAPISecret orders the results by the api_secret field.
func ByAPISecret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPISecret, opts...).ToFunc()
}
