// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ubgo/entkit/encryptedtype"
	"github.com/ubgo/entkit/examples/ent/predicate"
	"github.com/ubgo/entkit/jsonmap"
	"github.com/ubgo/entkit/passwordtype"
	"github.com/ubgo/jsonslice"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMetadata, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTags, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// APISecret applies equality check predicate on the "api_secret" field. It's identical to APISecretEQ.
func APISecret(v encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAPISecret, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v jsonmap.JsonMap) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMetadata, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v jsonslice.JsonSlice) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTags, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v passwordtype.HashedPassword) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v passwordtype.HashedPassword) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldContains(FieldPassword, vc))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v passwordtype.HashedPassword) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldHasPrefix(FieldPassword, vc))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v passwordtype.HashedPassword) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldHasSuffix(FieldPassword, vc))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v passwordtype.HashedPassword) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldEqualFold(FieldPassword, vc))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v passwordtype.HashedPassword) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldContainsFold(FieldPassword, vc))
}

// APISecretEQ applies the EQ predicate on the "api_secret" field.
func APISecretEQ(v encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAPISecret, v))
}

// APISecretNEQ applies the NEQ predicate on the "api_secret" field.
func APISecretNEQ(v encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAPISecret, v))
}

// APISecretIn applies the In predicate on the "api_secret" field.
func APISecretIn(vs ...encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldIn(FieldAPISecret, vs...))
}

// APISecretNotIn applies the NotIn predicate on the "api_secret" field.
func APISecretNotIn(vs ...encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAPISecret, vs...))
}

// APISecretGT applies the GT predicate on the "api_secret" field.
func APISecretGT(v encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldGT(FieldAPISecret, v))
}

// APISecretGTE applies the GTE predicate on the "api_secret" field.
func APISecretGTE(v encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAPISecret, v))
}

// APISecretLT applies the LT predicate on the "api_secret" field.
func APISecretLT(v encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldLT(FieldAPISecret, v))
}

// APISecretLTE applies the LTE predicate on the "api_secret" field.
func APISecretLTE(v encryptedtype.EncryptedString) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAPISecret, v))
}

// APISecretContains applies the Contains predicate on the "api_secret" field.
func APISecretContains(v encryptedtype.EncryptedString) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldContains(FieldAPISecret, vc))
}

// APISecretHasPrefix applies the HasPrefix predicate on the "api_secret" field.
func APISecretHasPrefix(v encryptedtype.EncryptedString) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldHasPrefix(FieldAPISecret, vc))
}

// APISecretHasSuffix applies the HasSuffix predicate on the "api_secret" field.
func APISecretHasSuffix(v encryptedtype.EncryptedString) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldHasSuffix(FieldAPISecret, vc))
}

// APISecretEqualFold applies the EqualFold predicate on the "api_secret" field.
func APISecretEqualFold(v encryptedtype.EncryptedString) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldEqualFold(FieldAPISecret, vc))
}

// APISecretContainsFold applies the ContainsFold predicate on the "api_secret" field.
func APISecretContainsFold(v encryptedtype.EncryptedString) predicate.User {
	vc := v.String()
	return predicate.User(sql.FieldContainsFold(FieldAPISecret, vc))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
